
work_dir: ./work_dir/default

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xset/train_data_joint.npy
  label_path: ./data/ntu120/xset/train_label.pkl

  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_joint.npy
  label_path: ./data/ntu120/xsub/val_label.pkl


# model
model: model.dualhead_net.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  num_gcn_scales: 9    # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph_msg3d.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [40, 60, 80]

# training
device: [0, 1, 2, 3]
batch_size: 64
forward_batch_size: 64
test_batch_size: 64
nesterov: True
seed: 666

